<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>nuspec</string>
	</array>
	<key>name</key>
	<string>NuGet</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>text.xml</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.xml.nuspec</string>
	<key>uuid</key>
	<string>D3C4E6DA-6B1C-11D9-8CC2-000D93589AF6</string>
</dict>
</plist>